### PR TITLE
Bug fixed

### PR DESCRIPTION
**Pull request by JeanPhilippeKernel**
I fixed some bugs like Colors changing, editing property of PowerMode.
Now you can change Colors or others properties configuration  as you want and it takes effect immediatly  :) , So try it and enjoy

### CODE REVIEW

**Comment by parnic** [comment]
Needs to be updated to latest rev. The PR has conflicts currently.

**Comment by JeanPhilippeKernel** [comment]
Oohh ok , I see it

**Comment by JeanPhilippeKernel** [comment]
I don't understand why I cant PR , dont see the problem

**Comment by parnic** [comment]
Your branch is out of date with the origin. You need to pull in the latest origin changes and merge them.

**Comment by JeanPhilippeKernel** [comment]
Ok I'm trying

**Pull request closed without merging**
